version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-loadbalancer
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/root/certs
    ports:
      - 80:80
      - 443:443

networks:
  default:
    external:
      name: adapt
