version: "3"
services:
  nginx:
    build: .
    image: vijaynallagatla/nginx_modsecurity:1.0
    container_name: nginx-loadbalancer
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/root/certs
    ports:
      - 80:80
      - 443:443
